[project]
name = "op-bridge"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "mcp==1.4.1",
    "httpx==0.28.1",
    "python-dotenv==1.0.1",
    "authed",
    "requests>=2.32.3",
    "fastapi>=0.115.11",
]

[tool.uv.sources]
authed = { workspace = true }
